apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: 154647635698.dkr.ecr.ap-southeast-1.amazonaws.com/to-do-app-grp1:latest
          ports:
            - containerPort: 80